### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/noma#1]

**Comment by AnotherDroog** [comment]
I've added the first tests, maybe you can help improve coverage @nolim1t ?

**Comment by nolim1t** [comment]
Sounds good

**Comment by nolim1t** [comment]
the create wallet function is a bit hard to test, as those functions are only available if there is no wallet on LND.

Unless we wrote an LND mock which would be useful anyway so it could run on travis

**Comment by ln2max** [comment]
I'm currently just mocking up requests.get() and requests.post() so that the tests will run even if there is nothing else set up locally:
https://github.com/ln2max/noma/blob/lnd_tests/tests/test_lnd.py

**Comment by AnotherDroog** [comment]
Wow awesome work @ln2max
