### ISSUE TITLE
Add package dependencies for building noma

### ISSUE THREAD

**Issue by nolim1t** [lncm/noma#17]
Unable to build noma right now.

Would be great if theres a list of packages

**Comment by nolim1t** [comment]
You can add this into this PR https://github.com/lncm/noma/pull/16

**Comment by AnotherDroog** [comment]
Going to add requirements.txt which can be used with `pip install -r requirements.txt`

**Comment by nolim1t** [comment]
Thanks. you could add it into that PR too

**Comment by nolim1t** [comment]
Those dependencies should also be in https://github.com/lncm/pi-factory/blob/master/etc/init.d/lncm-post as currently noma would not build
