### ISSUE TITLE
Running noma voltage results in an error

### ISSUE THREAD

**Issue by nolim1t** [lncm/noma#18]
```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/vc/bin/vcgencmd': '/opt/vc/bin/vcgencmd
```

Possibly need to have this installed somehow or check this

**Comment by AnotherDroog** [comment]
Yes, this is related to a firmware package we `apk add` during `post-install`

I'll add every dependency required for complete functionality to `requirements.txt`. 

In contrast, `pip install noma` only installs the _minimum_ required dependencies

**Comment by AnotherDroog** [comment]
I've added `requirements.txt`, however since `vcgencmd` is part of a firmware package and not a python package it will have to be installed during an OS specific routine.

Raspbian should work out of the box, and our Alpine image will too, therefore I'll close this issue now.
