### ISSUE TITLE
lnd.py: apparently redundant code

### ISSUE THREAD

**Issue by ln2max** [lncm/noma#32]
This looks like redundant code that does not do anything, can anyone confirm? (and remove if so! If it's not redundant, we need to close the file handle, which is not done)
https://github.com/lncm/noma/blob/4c38f6f6e0e0eb0efcb254a6a75852ef0345388f/noma/lnd.py#L231-L234

**Comment by AnotherDroog** [comment]
I believe you're right, it's redundant.

I've merged your changes to my branch and will test before removing anything

**Comment by ln2max** [comment]
Incorporated into https://github.com/lncm/noma/pull/31
