### ISSUE TITLE
Vagrant breaks Python installation symlinks

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/noma#33]
When using `python3 setup.py develop` mode, after re-provisioning or running `vagrant rsync`, Python symlinks break resulting in `noma` to fail when run.

Any ideas @noaho ?

**Comment by noaho** [comment]
RSync --delete was removing the python cache. 

https://github.com/lncm/noma/commit/ca89cd69b844b85fa8688cde49b1045c5ff88ded
