### ISSUE TITLE
Moar of dem words PLZ

### ISSUE THREAD

**Issue by meeDamian** [lncm/noma#73]
Currently `noma` is very user-unfriendly, seems like the only help available is:

```
$ sudo noma --help
Noma [node management]

Usage:  noma start
        noma stop
        noma check
        noma logs
        noma info
        noma lnd create
        noma lnd backup
        noma lnd autounlock
        noma lnd autoconnect [<path>]
        noma lnd savepeers
        noma lnd connectapp
        noma lnd connectstring
        noma (-h|--help)
        noma --version

Options:
  -h --help     Show this screen.
  --version     Show version.
```

I've tried multiple variations:

```
man noma
noma help <cmd>
noma help
noma <cmd> --help
noma <cmd> -h
```

All to no avail.  It would be good to have each command explained at least briefly, because right now it's not only not clear what commands do, but also how to call them.

Ex. How do I stop `lnd`? `noma stop lnd` doesn't seems to do it.

```
$ sudo noma lnd backup
Warning: Identity file  ~/.ssh/id_ed25519 not accessible: No such file or directory.
ssh: Could not resolve hostname ssh-hostname: Temporary failure in name resolution
lost connection
```

Would also be nice to explain why it needs sudo for all commands…

**Comment by ln2max** [comment]
Maybe helpful:
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html

**Comment by AnotherDroog** [comment]
Valid points.

Just a note, we've removed the ability to stop individual containers in favour of letting `docker` and `docker-compose` do what they were designed for

Closing since a solution is proposed in #75
